// autoRange: [{ ms: startMonth(1-12), ds: startDay, me: endMonth, de: endDay }]
// Iterate in reverse → themes defined later win when date ranges overlap

// ── Core palettes ─────────────────────────────────────────────────────────────
const CORE = [
  {
    id: 'meraki',
    name: 'Meraki Classic',
    icon: '💅',
    desc: 'The original green & blue',
    primary:   '#2D7A5F',
    accent:    '#3D95CE',
    gradStart: '#2D7A5F',
    gradEnd:   '#3D95CE',
    dark:      '#0e1c14',
    bg:        '#f8f9fa',
    cardBg:    '#ffffff',
    border:    '#e8e8e8',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    // Pairs with the 'merakiSite' editorial homepage layout. Cream/ivory
    // background, ink (#302c29) text, gold (#c19a4a) accent — same palette
    // used in HeroMerakiSite. Makes the booking flow + queue + other
    // tm-themed surfaces feel like a continuation of the editorial homepage.
    id: 'merakiEditorial',
    name: 'Meraki Editorial',
    icon: '✦',
    desc: 'Ink + cream + gold (editorial)',
    primary:   '#c19a4a',
    accent:    '#302c29',
    gradStart: '#c19a4a',
    gradEnd:   '#a8853c',
    dark:      '#302c29',
    bg:        '#fbfaf8',
    cardBg:    '#faf6ef',
    border:    'rgba(193,154,74,.22)',
    text:      '#302c29',
    muted:     '#8a827a',
  },
  {
    id: 'blush',
    name: 'Blush Rose',
    icon: '🌸',
    desc: 'Deep rose to dusty pink',
    primary:   '#C2185B',
    accent:    '#E91E63',
    gradStart: '#880E4F',
    gradEnd:   '#D81B60',
    dark:      '#4a0028',
    bg:        '#fff5f8',
    cardBg:    '#ffffff',
    border:    '#fce4ec',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'rose_gold',
    name: 'Rose Gold',
    icon: '🌹',
    desc: 'Wine to warm rose gold',
    primary:   '#9B3B5C',
    accent:    '#C49A7A',
    gradStart: '#7B2D46',
    gradEnd:   '#C49A7A',
    dark:      '#3d1020',
    bg:        '#fff8f6',
    cardBg:    '#ffffff',
    border:    '#f2ddd8',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'gold',
    name: 'Gold Luxe',
    icon: '✨',
    desc: 'Champagne & warm gold',
    primary:   '#A0760A',
    accent:    '#C9A227',
    gradStart: '#4A3500',
    gradEnd:   '#C9A227',
    dark:      '#2a1e00',
    bg:        '#fffdf0',
    cardBg:    '#ffffff',
    border:    '#e8d99a',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'matcha',
    name: 'Matcha',
    icon: '🍵',
    desc: 'Earthy matcha green',
    primary:   '#3D7A2E',
    accent:    '#8FAD40',
    gradStart: '#2E5E22',
    gradEnd:   '#7C9E3A',
    dark:      '#152E10',
    bg:        '#f5f9ee',
    cardBg:    '#ffffff',
    border:    '#d0e5b8',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'sage',
    name: 'Sage & Sand',
    icon: '🌿',
    desc: 'Soft sage green to warm sand',
    primary:   '#5D6B58',
    accent:    '#C4A882',
    gradStart: '#3E5038',
    gradEnd:   '#C4A882',
    dark:      '#2a3028',
    bg:        '#faf8f4',
    cardBg:    '#ffffff',
    border:    '#e0d8c8',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'ocean',
    name: 'Ocean Breeze',
    icon: '🌊',
    desc: 'Deep teal to sky blue',
    primary:   '#006994',
    accent:    '#00B4D8',
    gradStart: '#006994',
    gradEnd:   '#0096C7',
    dark:      '#003a55',
    bg:        '#f0f9ff',
    cardBg:    '#ffffff',
    border:    '#bde0f0',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'cobalt',
    name: 'Cobalt Storm',
    icon: '💎',
    desc: 'Oxford blue to electric cobalt',
    primary:   '#1251CC',
    accent:    '#42A5F5',
    gradStart: '#0A2463',
    gradEnd:   '#1565C0',
    dark:      '#050F3A',
    bg:        '#f0f4ff',
    cardBg:    '#ffffff',
    border:    '#c5d5f5',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'lavender',
    name: 'Lavender Dream',
    icon: '💜',
    desc: 'Rich purple to soft violet',
    primary:   '#5C35CC',
    accent:    '#9575CD',
    gradStart: '#4527A0',
    gradEnd:   '#7E57C2',
    dark:      '#1a0059',
    bg:        '#faf5ff',
    cardBg:    '#ffffff',
    border:    '#ddd6fe',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'berry',
    name: 'Berry Crush',
    icon: '🫐',
    desc: 'Deep purple to wine berry',
    primary:   '#6A1B9A',
    accent:    '#E91E63',
    gradStart: '#4A148C',
    gradEnd:   '#880E4F',
    dark:      '#1A0040',
    bg:        '#faf5ff',
    cardBg:    '#ffffff',
    border:    '#e0c8f5',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'tropical',
    name: 'Tropical Heat',
    icon: '🌺',
    desc: 'Hot magenta to teal',
    primary:   '#AD1457',
    accent:    '#00838F',
    gradStart: '#AD1457',
    gradEnd:   '#00838F',
    dark:      '#5D0027',
    bg:        '#fff0f8',
    cardBg:    '#ffffff',
    border:    '#f0c0e0',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'sunset',
    name: 'Sunset Glow',
    icon: '🌅',
    desc: 'Burnt orange to deep violet',
    primary:   '#E64A19',
    accent:    '#9C27B0',
    gradStart: '#BF360C',
    gradEnd:   '#6A1B9A',
    dark:      '#7A1500',
    bg:        '#fff5f0',
    cardBg:    '#ffffff',
    border:    '#f5d5c0',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'midnight',
    name: 'Midnight',
    icon: '🌙',
    desc: 'Dark navy & electric teal',
    primary:   '#0891B2',
    accent:    '#818CF8',
    gradStart: '#0f172a',
    gradEnd:   '#1e40af',
    dark:      '#020617',
    bg:        '#f8f9fa',
    cardBg:    '#ffffff',
    border:    '#e8e8e8',
    text:      '#1a1a1a',
    muted:     '#aaa',
  },
  {
    id: 'noir',
    name: 'Noir',
    icon: '🖤',
    desc: 'Sleek charcoal & silver',
    primary:   '#3A3A3C',
    accent:    '#8E8E93',
    gradStart: '#1C1C1E',
    gradEnd:   '#48484A',
    dark:      '#000000',
    bg:        '#F2F2F7',
    cardBg:    '#ffffff',
    border:    '#D1D1D6',
    text:      '#1C1C1E',
    muted:     '#8E8E93',
  },
];

// ── Seasonal / Holiday ────────────────────────────────────────────────────────
// Order matters: later entries override earlier ones when date ranges overlap.
const SEASONAL = [
  {
    id: 'new_year',
    name: "New Year's",
    icon: '🥂',
    desc: 'Midnight gold & silver',
    primary:   '#B8970A',
    accent:    '#9CA3AF',
    gradStart: '#1a1a1a',
    gradEnd:   '#B8970A',
    dark:      '#000000',
    bg:        '#fafaf8',
    cardBg:    '#ffffff',
    border:    '#e8e0cc',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [
      { ms: 12, ds: 26, me: 12, de: 31 },
      { ms: 1,  ds: 1,  me: 1,  de: 5  },
    ],
    seasonal: { emoji: '🥂', dir: 'up' },
  },
  {
    id: 'valentine',
    name: "Valentine's Day",
    icon: '💝',
    desc: 'Deep crimson to hot pink',
    primary:   '#C62828',
    accent:    '#E91E63',
    gradStart: '#880E4F',
    gradEnd:   '#D32F2F',
    dark:      '#4a0012',
    bg:        '#fff5f7',
    cardBg:    '#ffffff',
    border:    '#ffc0cb',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [{ ms: 2, ds: 1, me: 2, de: 14 }],
    seasonal:  { emoji: '💝', dir: 'up' },
  },
  {
    id: 'st_patricks',
    name: "St. Patrick's Day",
    icon: '☘️',
    desc: 'Luck of the Irish green',
    primary:   '#1B6B2E',
    accent:    '#F4C430',
    gradStart: '#0A4A1A',
    gradEnd:   '#2E8B3A',
    dark:      '#073510',
    bg:        '#f0fff4',
    cardBg:    '#ffffff',
    border:    '#b8f0c8',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [{ ms: 3, ds: 10, me: 3, de: 17 }],
    seasonal:  { emoji: '☘️', dir: 'up' },
  },
  {
    id: 'spring',
    name: 'Spring Bloom',
    icon: '🌷',
    desc: 'Fresh green to coral peach',
    primary:   '#2E7D32',
    accent:    '#F4511E',
    gradStart: '#1B5E20',
    gradEnd:   '#E64A19',
    dark:      '#0a2e0a',
    bg:        '#f9fff5',
    cardBg:    '#ffffff',
    border:    '#c8e6c9',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [{ ms: 3, ds: 20, me: 5, de: 7 }],
    seasonal:  { emoji: '🌷', dir: 'up' },
  },
  {
    id: 'easter',
    name: 'Easter',
    icon: '🐣',
    desc: 'Pastel lavender to sky blue',
    primary:   '#7B52AB',
    accent:    '#5BA4CF',
    gradStart: '#6A0DAD',
    gradEnd:   '#4A90D9',
    dark:      '#2e004a',
    bg:        '#fdf5ff',
    cardBg:    '#ffffff',
    border:    '#e5d0f8',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [{ ms: 4, ds: 1, me: 4, de: 20 }],
    seasonal:  { emoji: '🐣', dir: 'up' },
  },
  {
    id: 'mothers_day',
    name: "Mother's Day",
    icon: '💐',
    desc: 'Hot pink to coral peach',
    primary:   '#C0175B',
    accent:    '#FF8F6B',
    gradStart: '#AD1457',
    gradEnd:   '#FF7043',
    dark:      '#5c0028',
    bg:        '#fff5f8',
    cardBg:    '#ffffff',
    border:    '#ffc8dc',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [{ ms: 5, ds: 8, me: 5, de: 14 }],
    seasonal:  { emoji: '💐', dir: 'up' },
  },
  {
    id: 'summer',
    name: 'Summer Vibes',
    icon: '☀️',
    desc: 'Warm coral & amber',
    primary:   '#E64A19',
    accent:    '#FF8F00',
    gradStart: '#BF360C',
    gradEnd:   '#FF8F00',
    dark:      '#6a1200',
    bg:        '#fffaf5',
    cardBg:    '#ffffff',
    border:    '#ffe0b2',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [{ ms: 6, ds: 21, me: 9, de: 22 }],
    seasonal:  { emoji: '☀️', dir: 'up' },
  },
  {
    id: 'fourth_of_july',
    name: '4th of July',
    icon: '🎆',
    desc: 'Red, white & blue fireworks',
    primary:   '#B22222',
    accent:    '#1A3B8A',
    gradStart: '#8B0000',
    gradEnd:   '#1C3A7A',
    dark:      '#4a0000',
    bg:        '#f8f8ff',
    cardBg:    '#ffffff',
    border:    '#c8d4f0',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [{ ms: 7, ds: 1, me: 7, de: 7 }],
    seasonal:  { emoji: '🎆', dir: 'up' },
  },
  {
    id: 'halloween',
    name: 'Halloween',
    icon: '🎃',
    desc: 'Spooky dark & burnt orange',
    primary:   '#D35400',
    accent:    '#8E44AD',
    gradStart: '#1a0410',
    gradEnd:   '#D35400',
    dark:      '#0d0007',
    bg:        '#fdf3e7',
    cardBg:    '#ffffff',
    border:    '#f5cba7',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [{ ms: 10, ds: 1, me: 10, de: 31 }],
    seasonal:  { emoji: '🎃', dir: 'up' },
  },
  {
    id: 'thanksgiving',
    name: 'Thanksgiving',
    icon: '🦃',
    desc: 'Warm autumn harvest',
    primary:   '#B5451B',
    accent:    '#D4842E',
    gradStart: '#5C2A00',
    gradEnd:   '#D4842E',
    dark:      '#2e0f00',
    bg:        '#fdf7ef',
    cardBg:    '#ffffff',
    border:    '#f5dcc8',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [{ ms: 11, ds: 1, me: 11, de: 30 }],
    seasonal:  { emoji: '🍂', dir: 'up' },
  },
  {
    id: 'christmas',
    name: 'Christmas',
    icon: '🎄',
    desc: 'Forest green & crimson red',
    primary:   '#1B5E20',
    accent:    '#C62828',
    gradStart: '#1B5E20',
    gradEnd:   '#B71C1C',
    dark:      '#0a2e0a',
    bg:        '#f5fff5',
    cardBg:    '#ffffff',
    border:    '#c8e6c9',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [{ ms: 12, ds: 1, me: 12, de: 25 }],
    seasonal:  { emoji: '❄️', dir: 'down' },
  },
  {
    id: 'hanukkah',
    name: 'Hanukkah',
    icon: '🕎',
    desc: 'Royal blue & silver',
    primary:   '#0B3D91',
    accent:    '#A8B8D0',
    gradStart: '#071D56',
    gradEnd:   '#1565C0',
    dark:      '#020C30',
    bg:        '#f0f4ff',
    cardBg:    '#ffffff',
    border:    '#c0d0f0',
    text:      '#1a1a1a',
    muted:     '#aaa',
    autoRange: [{ ms: 12, ds: 15, me: 12, de: 23 }],
    seasonal:  { emoji: '🕎', dir: 'up' },
  },
];

export const THEMES       = [...CORE.map(t => ({ ...t, autoRange: null, seasonal: null })), ...SEASONAL];
export const CORE_THEMES  = THEMES.filter(t => !t.autoRange);
export const HOLIDAY_THEMES = THEMES.filter(t => t.autoRange);

export function getTheme(id) {
  return THEMES.find(t => t.id === id) || THEMES[0];
}

export function detectAutoTheme() {
  const now = new Date();
  const m   = now.getMonth() + 1;
  const d   = now.getDate();
  // Iterate in reverse so later (more-specific) entries win
  for (let i = THEMES.length - 1; i >= 0; i--) {
    const t = THEMES[i];
    if (!t.autoRange) continue;
    for (const { ms, ds, me, de } of t.autoRange) {
      let inRange;
      if (ms === me) {
        inRange = m === ms && d >= ds && d <= de;
      } else if (ms < me) {
        inRange = (m === ms && d >= ds) || (m > ms && m < me) || (m === me && d <= de);
      } else {
        // Wraps year-end → year-start (e.g. Dec 26 – Jan 5)
        inRange = (m === ms && d >= ds) || m > ms || m < me || (m === me && d <= de);
      }
      if (inRange) return t;
    }
  }
  return null;
}
